steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - | 
          gcloud compute instances update-container "$_VM_NAME" --container-image="$_IMAGE_NAME" --zone "$_ZONE"
substitutions:
  _ZONE: ""
  _IMAGE_NAME: "" 
  _VM_NAME: ""