steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - | 
          gcloud compute instances update-container "$_VM_NAME" --zone "$_REGION"-a --container-image="$_IMAGE_NAME"
substitutions:
  _REGION: ""
  _IMAGE_NAME: "" 
  _VM_NAME: ""