name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image and Push to GCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create image name patern as var
        run: |
          echo "APP_IMAGE_NAME=${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-artifact-registry/rtb:${{ github.sha }}" >> $GITHUB_ENV

      - uses: "google-github-actions/auth@v2"
        id: "auth"
        name: "Auth to GCP"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: "access_token"
      
      - name: Build Docker Image
        working-directory: app
        run: docker build -t "${{ env.APP_IMAGE_NAME }}" .

      - uses: "docker/login-action@v3"
        name: "Docker login"
        with:
          registry: ${{ vars.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Push Docker Image to GCR
        run: docker push "${{ env.APP_IMAGE_NAME }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Get VM zone and set as var
        run: |
          echo ZONE=$(gcloud compute instances list ${{ vars.VM_NAME }} --format 'csv[no-heading](zone)') >> $GITHUB_ENV

      - name: Deploy app with cloud build
        run: |-
          gcloud builds submit --config=cloudbuild/deploy.yaml \
            --substitutions=_IMAGE_NAME="${{ env.APP_IMAGE_NAME }}",_VM_NAME="${{ vars.VM_NAME }}"_ZONE="${{ env.ZONE }}"